import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  deviceWallet: { marginTop: 12 },
  walletButton: {
    padding: 14,
    backgroundColor: '#E5EBDD',
    borderRadius: 14,
    alignItems: 'center',
  },
  walletButtonText: { color: '#173E35', fontWeight: '700', fontSize: 13 },
  walletNote: { fontSize: 10, lineHeight: 16, color: '#68776F', marginTop: 8 },
  root: { flex: 1, backgroundColor: '#F5F6F0' },
  header: {
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brand: {
    fontSize: 23,
    color: '#173E35',
    fontWeight: '800',
    letterSpacing: -1,
  },
  badge: { fontSize: 10, letterSpacing: 1.4, color: '#64766A' },
  tabs: {
    marginHorizontal: 0,
    flexDirection: 'row',
    backgroundColor: '#E5EBDD',
    padding: 4,
    borderRadius: 16,
    marginBottom: 8,
  },
  tab: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: 12 },
  tabActive: { backgroundColor: '#fff' },
  tabText: { fontSize: 13, color: '#68776F' },
  tabTextActive: { color: '#173E35', fontWeight: '700' },
  content: { paddingTop: 12, paddingBottom: 32 },
  balanceCard: {
    padding: 20,
    borderRadius: 24,
    backgroundColor: '#173E35',
    marginBottom: 18,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  overline: { fontSize: 10, letterSpacing: 1.4, color: '#B5CDBB' },
  network: {
    color: '#CBEE9F',
    fontSize: 13,
    paddingVertical: 8,
    paddingLeft: 12,
  },
  balance: {
    fontSize: 43,
    fontWeight: '600',
    color: '#F5F6F0',
    letterSpacing: -2,
  },
  rate: {
    fontSize: 18,
    fontWeight: '600',
    color: '#CBEE9F',
    marginTop: 4,
    marginBottom: 16,
  },
  physical: {
    fontSize: 11,
    color: '#B5CDBB',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#416354',
  },
  button: {
    backgroundColor: '#173E35',
    borderRadius: 17,
    padding: 16,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  disabled: { opacity: 0.45 },
  historyShortcut: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 18,
  },
  link: { color: '#24856B', fontSize: 13 },
  disclosure: { fontSize: 10, lineHeight: 16, color: '#68776F', marginTop: 12 },
  back: { alignItems: 'center', padding: 16 },
  muted: { color: '#68776F', fontSize: 13 },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#173E35',
    marginBottom: 10,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#DCE3D7',
    borderRadius: 14,
    padding: 14,
    color: '#173E35',
    fontSize: 14,
  },
  fill: { paddingVertical: 14 },
  note: { fontSize: 12, lineHeight: 19, color: '#68776F', marginBottom: 10 },
  error: { color: '#B74136', fontSize: 13, marginTop: 12 },
  networkPanel: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
  },
  networkOption: {
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: '#173E35',
    letterSpacing: -0.7,
  },
  languages: {
    flexDirection: 'row',
    padding: 3,
    backgroundColor: '#E5EBDD',
    borderRadius: 12,
  },
  language: { padding: 9, borderRadius: 10 },
  small: { fontSize: 13, color: '#173E35' },
  activity: {
    backgroundColor: '#fff',
    borderRadius: 18,
    marginTop: 10,
    padding: 14,
  },
  refundActivity: { backgroundColor: '#E6EEDD' },
  activityTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  activityBody: { flex: 1 },
  refundAmount: { color: '#24856B' },
  itemTitle: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '600',
    color: '#173E35',
  },
  date: { fontSize: 14, lineHeight: 20, color: '#52665A', marginTop: 6 },
  right: { alignItems: 'flex-end', maxWidth: '32%' },
  details: {
    borderTopWidth: 1,
    borderTopColor: '#DCE3D7',
    marginTop: 14,
    paddingTop: 12,
  },
  empty: { paddingVertical: 36, alignItems: 'center' },
});
